---
kind: Namespace
metadata:
  name: training
---
## needed for kubectl inside ssh
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: admin-training
  namespace: training
subjects:
  - kind: User
    name: training@containercluster.net
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io