{{ if .Values.rbac }}
kind: RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: {{ template "fullname" . }}
  namespace: default
  # namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"  
subjects:
  - kind: User # May be "User", "Group" or "ServiceAccount"
    name: user@ssh.containercluster.net
    # namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
{{ end }}